/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Sesion;


/**
 *
 * @author JSolorzano
 */
public class Editar extends javax.swing.JPanel {

    /**
     * Creates new form Agregar
     */
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraNavegacion = new com.alee.laf.panel.WebPanel();
        Contenido = new com.alee.laf.panel.WebPanel();
        Correo = new com.alee.laf.text.WebTextField();
        NombreImagen = new com.alee.extended.image.WebImage();
        Editar = new com.alee.laf.button.WebButton();
        Cancelar = new com.alee.laf.button.WebButton();
        Usuario = new com.alee.laf.text.WebTextField();
        ContrasenaImagen = new com.alee.extended.image.WebImage();
        Contrasena = new com.alee.laf.text.WebTextField();
        ContrasenaContrasenaImagen = new com.alee.extended.image.WebImage();
        ConfirmarContrasena = new com.alee.laf.text.WebTextField();
        ContrasenaContrasenaImagen1 = new com.alee.extended.image.WebImage();

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        Correo.setForeground(new java.awt.Color(51, 51, 51));
        Correo.setDoubleBuffered(true);
        Correo.setDrawBorder(false);
        Correo.setDrawFocus(false);
        Correo.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        Correo.setHideInputPromptOnFocus(false);
        Correo.setInputPrompt("Correo");
        Correo.setInputPromptFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        Correo.setInputPromptForeground(new java.awt.Color(102, 102, 102));

        NombreImagen.setMaximumSize(new java.awt.Dimension(25, 25));
        NombreImagen.setMinimumSize(new java.awt.Dimension(25, 25));
        NombreImagen.setPreferredSize(new java.awt.Dimension(25, 25));

        Editar.setText("Agregar");

        Cancelar.setText("Cancelar");

        Usuario.setForeground(new java.awt.Color(51, 51, 51));
        Usuario.setDoubleBuffered(true);
        Usuario.setDrawBorder(false);
        Usuario.setDrawFocus(false);
        Usuario.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        Usuario.setHideInputPromptOnFocus(false);
        Usuario.setInputPrompt("Usuario");
        Usuario.setInputPromptFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        Usuario.setInputPromptForeground(new java.awt.Color(102, 102, 102));

        ContrasenaImagen.setMaximumSize(new java.awt.Dimension(25, 25));
        ContrasenaImagen.setMinimumSize(new java.awt.Dimension(25, 25));
        ContrasenaImagen.setPreferredSize(new java.awt.Dimension(25, 25));

        Contrasena.setForeground(new java.awt.Color(51, 51, 51));
        Contrasena.setDoubleBuffered(true);
        Contrasena.setDrawBorder(false);
        Contrasena.setDrawFocus(false);
        Contrasena.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        Contrasena.setHideInputPromptOnFocus(false);
        Contrasena.setInputPrompt("Contrasena");
        Contrasena.setInputPromptFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        Contrasena.setInputPromptForeground(new java.awt.Color(102, 102, 102));

        ContrasenaContrasenaImagen.setMaximumSize(new java.awt.Dimension(25, 25));
        ContrasenaContrasenaImagen.setMinimumSize(new java.awt.Dimension(25, 25));
        ContrasenaContrasenaImagen.setPreferredSize(new java.awt.Dimension(25, 25));

        ConfirmarContrasena.setForeground(new java.awt.Color(51, 51, 51));
        ConfirmarContrasena.setDoubleBuffered(true);
        ConfirmarContrasena.setDrawBorder(false);
        ConfirmarContrasena.setDrawFocus(false);
        ConfirmarContrasena.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        ConfirmarContrasena.setHideInputPromptOnFocus(false);
        ConfirmarContrasena.setInputPrompt("Confirmar Contrasena");
        ConfirmarContrasena.setInputPromptFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        ConfirmarContrasena.setInputPromptForeground(new java.awt.Color(102, 102, 102));

        ContrasenaContrasenaImagen1.setMaximumSize(new java.awt.Dimension(25, 25));
        ContrasenaContrasenaImagen1.setMinimumSize(new java.awt.Dimension(25, 25));
        ContrasenaContrasenaImagen1.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ContenidoLayout.createSequentialGroup()
                            .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(ContrasenaContrasenaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContenidoLayout.createSequentialGroup()
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(ContrasenaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContenidoLayout.createSequentialGroup()
                            .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(NombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContenidoLayout.createSequentialGroup()
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78)
                            .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(ConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ContrasenaContrasenaImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ContrasenaImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ContrasenaContrasenaImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ContrasenaContrasenaImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.panel.WebPanel BarraNavegacion;
    private com.alee.laf.button.WebButton Cancelar;
    public com.alee.laf.text.WebTextField ConfirmarContrasena;
    private com.alee.laf.panel.WebPanel Contenido;
    public com.alee.laf.text.WebTextField Contrasena;
    private com.alee.extended.image.WebImage ContrasenaContrasenaImagen;
    private com.alee.extended.image.WebImage ContrasenaContrasenaImagen1;
    private com.alee.extended.image.WebImage ContrasenaImagen;
    public com.alee.laf.text.WebTextField Correo;
    private com.alee.laf.button.WebButton Editar;
    private com.alee.extended.image.WebImage NombreImagen;
    public com.alee.laf.text.WebTextField Usuario;
    // End of variables declaration//GEN-END:variables
}
